# https://taskfile.dev

version: "3"

tasks:
  dev:
    cmds:
      - poetry run python main.py

  dev:ui:
    cmds:
      - npm --prefix geochem-portal-ui run dev

  test:
    cmds:
      - poetry run pytest
