name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: npm

      - name: Build UI
        working-directory: geochem-portal-ui
        run: |
          npm ci
          npm run build

      - uses: actions/checkout@v3

      - name: Upload UI artifacts
        uses: actions/upload-pages-artifact
        with:
          path: geochem-portal-ui/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
